### ISSUE TITLE
PO Approval mechanism

### ISSUE THREAD

**Issue by rodjular** [Symphony-CSCC/ivs_rcs#18]
Purchaser cannot submit PO(from PR) greater than 10K.
FM will submit PO for approval of GM.

Purchaser can always submit ML to FM for approval with no restriction.

**Amount can be controlled via IvsControl

**Comment by Apbasanez** [comment]
Dick gusto ni GM na yung ma view only sa P.O Monitoring under submitted is lahat lang nang a-approbahan nya. Ngayon kasi kahit below 10k makikita parin nya under submitted P.O.

**Comment by rodjular** [comment]
Additional filter to Jun sa Transaction Monitor and was told by Ms. Hon before I leave. I'm working on it. Will update you tomorrow. Thanks!
