### ISSUE TITLE
Cannot Process P.O when Item has apostrophe

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#25]
![p o dont accept item with apostrophe](https://cloud.githubusercontent.com/assets/28379241/25841550/1c765072-34d3-11e7-9085-b9cfe9b40b35.jpg)

**Comment by Apbasanez** [comment]
KG - Beef Tenderloin, Local, Whole, Jam's 
   make it to
     KG - Beef Tenderloin, Local, Whole, Jam s

I already did change from the item maintenance dick, but the PR didnt change thats why we cannot proceed with the P.O. Kindly change muna manually since we still tried to change all the items with (') or can we make the system accept (') on the items?

**Comment by rodjular** [comment]
![2017-05-09_221830 - copy](https://cloud.githubusercontent.com/assets/28424354/25855546/0c90bfa2-3506-11e7-9b6c-783f97d8d127.jpg)
I manage to find a solution without changing item name with apostrophe. You may still retain items with apostrophe.

I already updated the application. Please check tomorrow. 

I also fix the truncate error on canceling PO. PO # 774 is already canceled.

**Comment by Apbasanez** [comment]
Ok na Dick. Thanks. Di nalang natin i-close yung issue noh? para may tracing tayo?

**Comment by rodjular** [comment]
OK lang close. lipat lang naman sya sa Closed tab. Para maiwan sa Open mga on-going or unresolved items
