### ISSUE TITLE
Error when Printing P.O (merged P.R)

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#26]
![error when printing p o under merged pr](https://cloud.githubusercontent.com/assets/28379241/25886469/49c35134-3590-11e7-83cd-a2c3660296b7.jpg)

Hi Dick - magerror sya pag magprint ng P.O (merged P.R) ok lang yung ibang P.O pag hindi merged yung P.R. Thanks.

**Comment by rodjular** [comment]
Error Fixed. Please check.
