### ISSUE TITLE
Cannot re-P.O cancelled PR.

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#27]
![image](https://cloud.githubusercontent.com/assets/28379241/26024018/6caa9c62-37fb-11e7-949a-3b60e05b0edd.png)

Dick- please check P.O 592. I already cancelled the said P.O, but sir felix cannot re-P.O (see image error)

**Comment by rodjular** [comment]
Hi Jun,
    I already update the patch on PO. Please check with Sir Felix. Thanks!

**Comment by Apbasanez** [comment]
OK na Dick. Thanks.
