### ISSUE TITLE
Error on Goods Receipts

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#28]
![image](https://cloud.githubusercontent.com/assets/28379241/26093226/8d723bdc-3a47-11e7-8e76-289ad0f9026d.png)

Hi Dick- please help. Thanks.

**Comment by rodjular** [comment]
Jun, 
The original design of RR is it should not accept same Item ID. Since it is allowed in PR and PO, I updated Goods Receipt to do the same. Inventory is already updated please check with Matet. Thanks! 
Note: Exit and log off properly for the update to take effect.

**Comment by Apbasanez** [comment]
OK na dick as per Matet. Thanks.
