### ISSUE TITLE
ML#925 P.O Basis

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#29]
Hi Dick - ask ko lang. If may check na yung ML Requisition means may P.O na?
![image](https://cloud.githubusercontent.com/assets/28379241/26232663/6008ff10-3c8a-11e7-9bab-ca78f0eaa97a.png)
 Yung ML#925 kasi sabi ng user e hindi nya daw o wala daw Cash Payment na checkbox sa ML nya, dapat daw ma-P.O na ni sir felix, but sir felix di na ma.P.O kasi naka cash basis daw. I checked the logs di ako sure if si chef brian ba nagcheck ng cash payment box bago nya inaprroved. Sino lang ba pwede makapag check ng cash payment box? yung MRequestor o yung approving head? Pwede natin mabalik yung ML # 925 na P.O Basis. Thanks.

**Comment by rodjular** [comment]
Jun, 
     Approved na yung ML eh di na natin maibabalik yan unless i cancel na yung ML then i re PO. Part of the business rule na naincorporate natin sa program.  Baka aksidente na i click yung Cash Basis.

**Comment by Apbasanez** [comment]
Hi Dick - yes cancel nalang namin kaso wala akong rights to cancel as admin. Sino pwede maka-cancel? Thanks.

**Comment by Apbasanez** [comment]
![image](https://cloud.githubusercontent.com/assets/28379241/26236790/b950f694-3ca4-11e7-8f92-3c716dd5a2d9.png)
 Dick hindi ko ma-cancel ang P.O. Thanks.

**Comment by rodjular** [comment]
Basta may role ng DEPTHEAD. pwede ma cancel. but I also uncheck the NoDelete Support flag sa MR kaya pala di allow maka cancel. Exit and logout lang properly then. pa try i cancel.
