### ISSUE TITLE
Error in issuance report

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#31]
![image](https://cloud.githubusercontent.com/assets/28379241/26238085/24e70cd6-3caa-11e7-9c91-d3966f79d86c.png)

**Comment by rodjular** [comment]
Hi Jun, Install mo lang ReportViewer v10. You my download it sa Microsoft website or baka meron na endorse sayo si Jenon na..

**Comment by Apbasanez** [comment]
Ok na Dick. Akala ko na-installan ko na lahat ng PC ng reports viewer hehehe. Kala ko bugs. :)
