### ISSUE TITLE
Show Form Tab on Inventory Transaction Monitor

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#32]
Hi Dick-Goodnoon,

Paano ishow yung Cost Transfer Tab Sa Inventory Transaction Monitor? or yung ibang Forms. Thanks
![image](https://cloud.githubusercontent.com/assets/28379241/26298092/7389dca0-3f08-11e7-937b-fb867560c8a9.png)

**Comment by rodjular** [comment]
Jun, 
    User must have a Cost Controller or Department Head role.

**Comment by Apbasanez** [comment]
Ok Got it Dick. Thanks.

**Comment by Apbasanez** [comment]
Hi Dick, im trying to check the cost controller roles but the tab shown will be Purchased Order.

**Comment by rodjular** [comment]
try mo dept head
