### ISSUE TITLE
No Cost Transfers reflected for the Month of May

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#33]
![image](https://cloud.githubusercontent.com/assets/28379241/26346059/98640a1c-3fd7-11e7-839b-0ea2e852d012.png)
![image](https://cloud.githubusercontent.com/assets/28379241/26346067/9c7a9198-3fd7-11e7-9d3e-ac38cc80c645.png)

**Comment by rodjular** [comment]
Jun, 
    Issue already fixed. May kulang lang sa update ko. Pa check na lang with Ms.Kathy. Thanks!

**Comment by Apbasanez** [comment]
Ok na Dick. Thanks.
