### ISSUE TITLE
Bugs on Good Receipts

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#34]
![image](https://cloud.githubusercontent.com/assets/28379241/26435024/d8dc9aba-413e-11e7-8eab-62b856da9844.png)

**Comment by Apbasanez** [comment]
Hi Dick nawala rin yung Acknowledge By sa ibaba ng Godds Receipt printout ni Matet. Pls. check at pakibalik na rin. Thanks.
![image](https://cloud.githubusercontent.com/assets/28379241/26435100/679427b4-413f-11e7-830f-29fad8501d17.png)

**Comment by rodjular** [comment]
Jun,
     Just tried it sa server working fine naman. Note that 'Acknowledge By ' will appear if may laman yung Cost Center (Direct Issue). 
     Baka lang nag break yung program for some reason.
![rr1220](https://cloud.githubusercontent.com/assets/28424354/26435342/316cb712-4141-11e7-8e68-8a8cf03c973a.jpg)
