### ISSUE TITLE
Wrong approving officer appear in PR

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#35]
![image](https://cloud.githubusercontent.com/assets/28379241/26441963/30711f0a-4165-11e7-8d0f-15f31fd4c951.png)

Hi Dick - please check approving of PR. Kay Abella Sharon yung lumalabas instead of Brian. Thanks.

**Comment by rodjular** [comment]
String or binary data will be truncated - Reduce characters in remarks field. Extending char size is still on going. Default kasi si Ms Abella, Sharon in F& B Production anyway pag inapprove naman yan ni chef pa override din yung approval name.
