### ISSUE TITLE
Error when creating new Issuance

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#36]
![image](https://cloud.githubusercontent.com/assets/28379241/26487367/ce6af6f0-4231-11e7-97d9-1092063e6bba.png)

**Comment by rodjular** [comment]
Hi Jun,
     Unsa Stores Requisition # nito?

**Comment by Apbasanez** [comment]
Dick - everytime magcreate kami ng bagong issuance, mag appear yung error. Same din sa server. Thanks.

**Comment by rodjular** [comment]
Jun, pa test ulet. May mga updates kasi ako. Let me know kung ok na.

**Comment by rodjular** [comment]
pa log out properly(super exit) to take effect changes.

**Comment by Apbasanez** [comment]
Ok na Dick. Thanks.
