### ISSUE TITLE
Change fax # from P.O 8605 to 8603

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#37]
![image](https://cloud.githubusercontent.com/assets/28379241/26717948/cce2e4ca-47b1-11e7-8860-4d257e317676.png)

**Comment by rodjular** [comment]
Hi Jun,
   8605 to 8603 or 8603 to 8605?

**Comment by Apbasanez** [comment]
8605 to 8603 dick. 8605 kasi existing ngayon. Thanks.

**Comment by Apbasanez** [comment]
change 8605 to 8603 dick. tanggalin natin yung 8605.

**Comment by rodjular** [comment]
Jun, update done. Pls check with Jospeh.
