### ISSUE TITLE
Cannot Update Month end Inventory

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#38]
![image](https://user-images.githubusercontent.com/28379241/26860068-7d531720-4b6e-11e7-83ed-8211d4ecb892.png)

**Comment by rodjular** [comment]
Hi Jun,
   Update done. Note that during month-end will take a while and screen will look not responding. Please patiently wait until 'Update done' prompt appears as confirmation that it is finished. Thanks!
