### ISSUE TITLE
Storeroom Request - Unit

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#41]
Why does the purchase unit appear instead of the store unit?

![2017-07-02 18_48_03-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27769216-e362ad44-5f57-11e7-848a-7ae91559e8ec.png)
![2017-07-02 18_51_09-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27769217-e5acb69e-5f57-11e7-9a68-38879605365f.png)

**Comment by rcjular** [comment]
Hi Chef. Will check on this. Purchase unit is to PR and Store Unit is to SR.

**Comment by bltbersonda** [comment]
Thanks.

**Comment by bltbersonda** [comment]
Dick, we discovered that the store unit ID is still used here because when lennard opens the request to make an issuance, Store Unit is used. So probably it is just the $string value (from PU) that is concatenated to the item name that's wrong when displaying the particulars in the Storeroom Request Form.

**Comment by rcjular** [comment]
Chef, Yes. Its a concatenated string value of PU and Item name for Particulars(as item preference). Actually, it was patterned with PR thus the PU was used instead of SU which is wrong. I was on leave the past two days, I'm already working on this now and will give you update within the day. Thanks!

**Comment by rodjular** [comment]
FIX_20170706 were applied please check. Exit and log out properly for changes to take effect.

**Comment by bltbersonda** [comment]
Thanks for the update!
