### ISSUE TITLE
Inactive Items can be PR'ed

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#42]
When making a marketlist or PR, inactive items can be added. Should not be allowed.

![2017-07-04 14_18_56-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27817548-550bcb20-60c4-11e7-9518-432d7fda691d.png)
![2017-07-04 14_19_57-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27817561-698eced0-60c4-11e7-8445-bccc92be3b09.png)

**Comment by rcjular** [comment]
Hi Chef, generic does not maintain a status. Generic table is independent and does not inherits item status. We only link the generic id in the Item table. The only effect on PR of inactive item, is it will not be shown in Item Preference lookup (Particulars field).

**Comment by bltbersonda** [comment]
Ok. This is safe. Purchaser cannot make PO w/o the specific item since it is disabled?

I have a similar issue on the Cost Transfer Form w/c may have a different effect on the database.

**Comment by bltbersonda** [comment]
Dick, FYI, Item Preference lookup from the Particulars Field still displays inactive items.

**Comment by rodjular** [comment]
Noted. Just waiting from Jun's reply. Can't connect via team viewer.

**Comment by rodjular** [comment]
FIX_20170706 were applied please check. Exit and log out properly for changes to take effect.

**Comment by bltbersonda** [comment]
Thanks for the update.

When adding an inactive item, this appears after choosing from the Particulars
![2017-07-06 16_52_09-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27903481-16fe8b2a-626c-11e7-9ff4-11768e019fce.png)

NOTE: Dingdong is currently an inactive item

**Comment by rodjular** [comment]
Hi Chef, 
      Already patch Item preference lookup for particulars. please check. 
![marketlis_particulars_lookup](https://user-images.githubusercontent.com/28424354/27943912-dc037a54-6297-11e7-8db2-4e147adbda45.PNG)

**Comment by bltbersonda** [comment]
Thanks.

Issue is now closed.
