### ISSUE TITLE
Inactive Items can be used in Cost Transfers

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#43]
User was able to add items to the form even if the items were set to Inactive
![2017-07-04 21_54_31-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27833109-dfcab958-6103-11e7-9d25-4285c042e56a.png)

![2017-07-04 21_56_25-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27833127-fd60ce6c-6103-11e7-8208-291c49b568b0.png)
![2017-07-04 21_57_26-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/27833128-00586a62-6104-11e7-97b7-c3ce78475e07.png)

**Comment by rodjular** [comment]
FIX_20170706 were applied please check. Exit and log out properly for changes to take effect.

**Comment by bltbersonda** [comment]
Thanks.

This issue is now closed.
