### ISSUE TITLE
Error on Goods Receipt - Ever HRI Sales

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#48]
![image](https://user-images.githubusercontent.com/28379241/27949385-1b3e9832-6330-11e7-9115-a70432059a92.png)
![image](https://user-images.githubusercontent.com/28379241/27949395-2122cf16-6330-11e7-8c43-76ee8ff8743c.png)

Hi Dick - please check. Error yung ever hri sales pag mag RR kami.

**Comment by rodjular** [comment]
Hi Jun, probably error occurred during the time of updating Symphony last friday. Ok naman na upon checking. Apparently, same error with issuance reported by Ms. Hon this morning which is already fixed. Pls check. Thanks!

**Comment by Apbasanez** [comment]
Ok na Dick. Thanks.
