### ISSUE TITLE
Stores Requisition Lag

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#52]
Hi Dick,

There is a noticeable lag when opening and closing Store Request Form. Takes about 7 seconds to open and about 5 seconds to close (after approving).

Can this be corrected?

**Comment by bltbersonda** [comment]
Hi Dick,

Can we possibly look into this? We noticed that the lag has now increased to about 20 seconds already before we can open a Store Request form

**Comment by rodjular** [comment]
Hi Chef,
     Already made some optimizations in stores requisition query. Please check medyo pas pas na. ; )
