### ISSUE TITLE
Cannot Cancel Cost Transfer

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#53]
![image](https://user-images.githubusercontent.com/28379241/28056107-3f992f32-664e-11e7-8ee7-236e6ed1d4ad.png)

**Comment by rodjular** [comment]
Jun, I already extended particulars length. This will also fixed the intermittent error "String or binary data would be truncated."

**Comment by rodjular** [comment]
Please check. Thanks!

**Comment by Apbasanez** [comment]
OK na to Dick Thanks.
