### ISSUE TITLE
Production Reports

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#55]
Dick,

What reports should we access to check:

1. Cost of production (price per yield)
2. Inventory movement (where the yield was added, and the ingredients that were subrtracted because of the production)

**Comment by rodjular** [comment]
1. Production Report from Production Entry. button on the lower left of the window.
2. You may check Cost Center Item Console.

**Comment by bltbersonda** [comment]
Thanks.

For Production Report, is it possible to add Cost per Yield-Unit?

![2017-07-17 18_11_22-print preview](https://user-images.githubusercontent.com/29772640/28264129-1aec50d8-6b1c-11e7-942c-e56dcdcd1b3c.png)

**Comment by rodjular** [comment]
Please check.
![prod_report_costperportion](https://user-images.githubusercontent.com/28424354/28352674-6261c12c-6c8a-11e7-854e-c315cbaf3635.JPG)

**Comment by bltbersonda** [comment]
Thanks.

Thread closed
