### ISSUE TITLE
Error on Goods Receipt

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#57]
Hi Dick please help

![image](https://user-images.githubusercontent.com/28379241/28153125-5eb9f476-67d6-11e7-9395-4b650a12d848.png)

**Comment by rodjular** [comment]
Anong action supposed to be gagawin niMatet? Mag save ba? print ng RR?

**Comment by Apbasanez** [comment]
i cancel sana dick

**Comment by rodjular** [comment]
Jun, fix applied. Exit and logout properly to take effect. Thanks!
