### ISSUE TITLE
Item Search @ actual inventory count posting & beg balances set-up

### ISSUE THREAD

**Issue by yenohq** [Symphony-CSCC/ivs_rcs#58]
Dick,

Please add "item search" button for actual inventory count posting & beg balances set-up.
It's time consuming to encode such counts per item.

ASAP please and thank you.

**Comment by rodjular** [comment]
Hi Miss, Hon. Working on it. Check ko rin yung problem ni Matet eh. Bukas tapos na to. THanks!

**Comment by rodjular** [comment]
Hi Ms. Hon,
    Sorry for the delay. Update Done. Please check Beginning Balances and Actual Count entry for both store and cost center.
![actual_begbal](https://user-images.githubusercontent.com/28424354/28352781-f28cfc1c-6c8a-11e7-89c5-20515a61a971.JPG)

**Comment by rodjular** [comment]
My term is a filter but will work as a search field as described in your requirements. Thanks and regards : )

**Comment by yenohq** [comment]
Noted Dick and hoping to have it before July will end.
