### ISSUE TITLE
Storeroom / Cost Center Relationships

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#59]
Hi Dick,

Need clarification. See image below.

![2017-07-14 18_31_54-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/28209341-b487a4b8-68c4-11e7-8c5d-52eefda094d9.png)

My understanding is, all open forms on the screenshot all refer to B88 - Asian Lime Barbecue Ribs. However, the items in red rectangles can get confusing. I'd like to clarify the difference between them so we can set up the recipes correctly and hopefully, we can adjust how we make our manual reports to correspond with the software. There are 4 open forms in the screenshot (clockwise): Item Maintenance, Generic Name, Recipe Definition - By Generic and Production Entry.

Questions:
1. Is #1 the the one used in Cost Transfer, Store Request, Market List? or #2?
2. does #1 inherit #2? What happens if Store ID is different in #2  & #1? 
3. how does #5 differ from #6? What happens if StoreID is in #5 and not in #6 (and vice versa)?
4. what is the use of #3?
5.  when making a production entry, does #3 have to be the same with #4? 

I look forward to your soonest reply.

Thanks.

**Comment by rodjular** [comment]
Hi Chef, 

1. Cost Transfer - # 1, Store Request # 2 and Market List # 2
2. Yes in setting up. But can no.1 can still be overridden(no restriction yet in setup). Different Store Id in # 2 and # 1 will have an effect in Store Requisition - Issuance and PR-PO linking. Item will not be available in lookup or cannot be selected.
3. Purpose of generic table (# 2) were used by Stores Requisition, Purchase Requests(including Market list) and Recipe Costing by Generic with # 6 serves as restriction. While actual item table (# 1) were used by Purchase Order, Goods Receipts, Issuance, Cost Transfers, Actual Count(Store and Cost Center), Recipe Cost by Item and Production with # 5 as restriction. Different # 5 and # 6 will have the same effect as with different store id.
4. It will determine the Cost Center of where an item will be deducted or added during POS sold item capture.
5. Not necessarily. 

Thanks and regards,
Dick

**Comment by bltbersonda** [comment]
Hi Dick,

Thanks for your clarification.

Further questions:
1. #3 is non-bearing when making a production? Meaning in making a production, #4 will be the the cost center where the ingredients will be subtracted and the yield will be added? As long as the Cost Center has the ingredients, they can make the production?
2. When making a production, Store Cost Center (#4) will be restricted to #1? or #2? or #5? or #6?

**Comment by rodjular** [comment]
1. Yes.
2. no 5 if item is for portioning. While if it is from Recipe(by generic) lookup restriction will be based on item's generic id.

**Comment by bltbersonda** [comment]
Perfect! We can just encode 1 recipe w/c can be "produced" in different cost centers.

 Thanks. 

Thread closed.
