### ISSUE TITLE
Cannot Issue Items on Storeroom

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#61]

**Comment by Apbasanez** [comment]
Hi Dick,

Please help, Lenard cannot issue of the ff. items. Ice Cream(Mango, nestle Classic) & Capers in Vinegar(Capri, Dr. 600g/bottle). They said they have stock this July.
![image](https://user-images.githubusercontent.com/28379241/28306434-dda252c0-6bd1-11e7-836a-91415d601acd.png)

![image](https://user-images.githubusercontent.com/28379241/28306460-f4227c0a-6bd1-11e7-8c05-5959a19d6ec9.png)

**Comment by rodjular** [comment]
Pa check ng item and generic setup
refer to #50

**Comment by bltbersonda** [comment]
![2017-07-18 16_43_30-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/28308314-5f3e77f4-6bd8-11e7-9b64-a8e9ec180c1d.png)

**Comment by rodjular** [comment]
ooopps Sorry. Kala ko sa setup. I assume sa qty may lumalabas na prompt. pwede makita yung prompt? I think may fix na ako dito. Thanks!

**Comment by Apbasanez** [comment]
![image](https://user-images.githubusercontent.com/28379241/28351154-a90bfb9c-6c80-11e7-8dee-21d032566c9c.png)

![image](https://user-images.githubusercontent.com/28379241/28351159-b21ca92a-6c80-11e7-9c53-19d5ac84caf9.png)

**Comment by Apbasanez** [comment]
![image](https://user-images.githubusercontent.com/28379241/28351172-c3582c32-6c80-11e7-8e6e-50d113f50dae.png)

**Comment by rodjular** [comment]
Hi Jun, Ms. Hon. zero balance as per July, 2017 kaya entry rejected. Nag add na alng ako prompt which Lenard can continue by clicking Yes button. Same validation with Item Id.

**Comment by rodjular** [comment]
Exit and logoff properly to take effect.

**Comment by Apbasanez** [comment]
May na RR daw dick sa july 5. Ma issue na ni lenard but yung UOM di magreflect.(see below image)
![image](https://user-images.githubusercontent.com/28379241/28355634-6f0a533c-6c97-11e7-9d84-f00adbe18e9b.png)
Then yung capers in vinegar na issue na ni lennard but walang price.

**Comment by Apbasanez** [comment]
eto yung RR# Dick.
![image](https://user-images.githubusercontent.com/28379241/28356123-75a30ae8-6c99-11e7-8488-99c2eede3df2.png)
![image](https://user-images.githubusercontent.com/28379241/28356180-aeed9cfa-6c99-11e7-8d0f-218951cb3271.png)

**Comment by rodjular** [comment]
Jun & Ms. Hon,
     Fix was already applied. Sa database side (view) ang problem. Paki check na lang po. Thanks!

**Comment by Apbasanez** [comment]
OK na Dick. Thanks.
