### ISSUE TITLE
Recipe Double Items

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#62]
Hi Dick,

We noticed an error when making a production for Cheesecake. We opened the recipe and noticed that there were two entries for Rum and Food Flavor Vanilla. We tried deleting one and saved it. When we opened the recipe again, both items were deleted. We added it again, saved and opened again. again 2 duplicate 
![2017-07-18 16_32_55-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/28307950-44cc5298-6bd7-11e7-8c64-e563c835e2bb.png)
items were added.

**Comment by rodjular** [comment]
Hi Chef, Fixed. Pls Check. Thanks!

**Comment by bltbersonda** [comment]
Thank you.

We will give this a try. Thread considered closed.
