### ISSUE TITLE
ML PO above 10K

### ISSUE THREAD

**Issue by yenohq** [Symphony-CSCC/ivs_rcs#67]
Hi Dick,

Please update the approval of PO.  As discussed with Ms. Mic... all ML PO is to be approved by me with assumption that bears small amount yet we really can't avoid that there are items or total amount of ML PO  is more than 10K specially meat items.  Thus, please amend ML PO procedure the same with the PR that all PO more 10K,  FM will submit for GM's approval.  

Thank you.

**Comment by rodjular** [comment]
Hi Ms Hon and Jun,
     PO submission already updated. Please monitor. Thanks!

**Comment by yenohq** [comment]
You mean the ML items above 10K?



*HONEYLENE Q. RODRIGUEZ*
Finance Manager
City Sports Club Cebu Inc.
Cardinal Rosales Ave., Cebu City
T  : (032) 415 8700 Local 200
M : 0917 637 3250
Email : finance.manager@citysportsclub.com

**Comment by rodjular** [comment]
Yes Ms. Hon.

**Comment by yenohq** [comment]
It's working now.

Thank you.

*HONEYLENE Q. RODRIGUEZ*
Finance Manager
City Sports Club Cebu Inc.
Cardinal Rosales Ave., Cebu City
T  : (032) 415 8700 Local 200
M : 0917 637 3250
Email : finance.manager@citysportsclub.com
