### ISSUE TITLE
Cost Center for Recipes

### ISSUE THREAD

**Issue by bltbersonda** [Symphony-CSCC/ivs_rcs#69]
Hi Dick,

How do we add Bistro Bar, La Veranda Bar and Banquet Bar to the Recipe Module Cost Center?

![2017-07-27 13_29_02-symphony cms 2 1 - city sports club cebu](https://user-images.githubusercontent.com/29772640/28655885-28d811ca-72d1-11e7-9fee-ff70dfce430a.png)

**Comment by rodjular** [comment]
Hi Chef,
    In Cost Center Maintenance, tick the production flag to add it at Recipe Definition form.
![costcentersetup](https://user-images.githubusercontent.com/28424354/28656449-a11adafc-72d4-11e7-9827-3fab8dccf110.JPG)

**Comment by bltbersonda** [comment]
Thanks, Dick

@Apbasanez Please enable for Bistro Bar, Banquet Bar and La Veranda Bar.

Thanks.

**Comment by Apbasanez** [comment]
Done Chef.

**Comment by bltbersonda** [comment]
Thread closed. Thanks
