### ISSUE TITLE
Error in creating new PR

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#75]
Hi Dick please check. Thanks.

![12](https://user-images.githubusercontent.com/28379241/29020792-bd4dd4f8-7b95-11e7-9bc7-30ee7757eddd.png)

**Comment by Apbasanez** [comment]
Also sa Storeroom Requisition.
![image](https://user-images.githubusercontent.com/28379241/29022624-ae6b8a28-7b9c-11e7-8ee7-69ca4998163e.png)

**Comment by rodjular** [comment]
Error Fixed. Please check.
