### ISSUE TITLE
Error in Saving RR

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#76]
![image](https://user-images.githubusercontent.com/28379241/29023178-2b58878c-7b9f-11e7-8b1a-d8f3015785fa.png)

**Comment by rodjular** [comment]
Jun, upon checking RR was already created. See attached. 
![rr_po2370](https://user-images.githubusercontent.com/28424354/29031815-fcdd6bfc-7bc1-11e7-8477-d643b3a59a1c.JPG)
