### ISSUE TITLE
SQL Server allocation

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#78]
Dick\Jen,

Eto yung server max ram ng SQL. Ilan yung i-allocate ko dito Dick?
![image](https://user-images.githubusercontent.com/28379241/29257096-e25283e2-80e1-11e7-97d8-13b247f845ca.png)
 Then sa database, ano yung pwede i delete na dito?
![image](https://user-images.githubusercontent.com/28379241/29257125-0d1993d6-80e2-11e7-8aa6-302b0d2925b5.png)

Bumagal kasi access namin sa server. Thanks.

**Comment by rodjular** [comment]
Jun,
    Set your total RAM 80 % sa SQL Server, 20% sa OS.
