### ISSUE TITLE
Cost Center Actual Count Document Not Found

### ISSUE THREAD

**Issue by Apbasanez** [Symphony-CSCC/ivs_rcs#79]
Hi Dick - dick nag encode kami sa hot kitchen na cost center actual count, makita namin na posted pero once i-open namin sabi nya Document Not Found Daw. Please check. Thanks.

![image](https://user-images.githubusercontent.com/28379241/29738994-769b34ea-8a65-11e7-9b38-261d578aa84c.png)

![image](https://user-images.githubusercontent.com/28379241/29738996-80f0a420-8a65-11e7-8ee8-96eb151e440b.png)

**Comment by Apbasanez** [comment]
Hi Dick Follow-up ko lang. Thanks.

**Comment by rcjular** [comment]
Hi Jun. Will check. Download ko database nyo.

**Comment by Apbasanez** [comment]
Ok dick.

 

JHUN P. BASAÑEZ

Network & Systems Administrator

CITY SPORTS CLUB, CEBU

Cardinal Rosales St. 

Cebu Business Park Cebu City

T: 63 32 4158700 loc 613

F: 63 32 4158605

M: 63 942 8684231| 

E: apbasanez@citysportsclub.com

www.citysportsclub.com

https://docs.google.com/uc?export=download&id=0B_5UPJ3bARw4QkRyOHVwc3djeGM&revid=0B_5UPJ3bARw4K2RLd080cEtSNjJxM0xNV1JCcFJPSXhHeTVjPQ

"from simple joys, new traditions are born"

**Comment by rcjular** [comment]
Hi Jun,
    Fixed. Please check.
